---
- hosts: 127.0.0.1
  connection: local
  vars:
    rest_hostname: {{ rest_hostname }}
    rest_port: {{ rest_port }}
    rest_endpoint: {{ rest_endpoint }}
    rest_json: '{{ rest_json }}'

  tasks:
  - debug: var=rest_json

  - name: Call Fabric REST API
    uri:
      url: http://{{ '{{' }} rest_hostname {{ '}}' }}:{{ '{{' }} rest_port {{ '}}' }}/{{ '{{' }} rest_endpoint {{ '}}' }} #http://localhost:8181/onos/v1/network/configuration/
      body: "{{ '{{' }} rest_json {{ '}}' }}"
      body_format: raw
      method: POST
      user: karaf
      password: karaf
